### ISSUE TITLE
User M365 detail tables are cut off

### ISSUE THREAD

**Issue by CorneliousJD** [lwhitelock/HuduM365Automation#6]
Some tables such as 

- User Details
- One Drive Details
- Mailbox Settings
- User Groups (if enough group memberships) 

all get cut off like this.
![image](https://user-images.githubusercontent.com/724777/162835649-4b890fef-090a-463e-9d2b-ed5f273e7749.png)

Is there a way this can be fixed so they have either scroll-bars, or each table is as long as it needs to be to fit all the data?

**Comment by kikkn** [comment]
Hi a colleague of me fixed it for us in the standalone script, by adding this:
"<div class="nasa__block" style="margin-bottom: 20px; overflow: visible!important; height: auto!important;">"
Instead of "<div class="nasa__block" style="margin-bottom: 20px;">" 
on line 414 https://github.com/lwhitelock/HuduM365Automation/blob/master/Standalone/M365-Hudu-Standalone.ps1
not quite sure where its in the azure function app.

**Comment by lwhitelock** [comment]
Sorry did you miss putting something in the "s or are you saying it needs an empty line somewhere?

**Comment by kikkn** [comment]
> Sorry did you miss putting something in the "s or are you saying it needs an empty line somewhere?

Forgot to add code parameters, so it got blank, should be updated now :)

**Comment by lwhitelock** [comment]
Ahh I realised I forgot to include details on my custom css in the ReadMe. I have added it in now which should fix this https://github.com/lwhitelock/HuduM365Automation/blob/master/README.md#custom-css

**Comment by CorneliousJD** [comment]
Confirming this fixed it for me 👍
